apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: usermgmt-restapp
  name: usermgmt-service
spec:
  ports:
  - port: 8095
    protocol: TCP
    targetPort: 8095
  selector:
    app: usermgmt-restapp
  type: NodePort
status:
  loadBalancer: {}
